Add new dev (Akeel) to Json. file
sef-global/sef-dev pull request #2
Opened 2021-07-11 16:00 UTC by akeel230

## Welcome PR details 

- SEF Hive User Name
Akeel_malik

- Introduce yourself thread entry url
https://sef.discourse.group/t/welcome-please-introduce-yourself/7/63

- How many Pull Requests have you sent to sef-repos? (Check only one)
  - [ ] This is the first one 
  - [ ] 2 Including this
  - [ ] 3 - 4 Including this
  - [x] 5 or more Including this 

## Approach
added the info in to the developer.Json file via the clone from the sef-dev repo 

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-07-15 18:37 UTC, Piumal1999 approved these changes

2021-07-19 07:33 UTC, Gravewalker666 requested changes
Hey, @akeel230 would you be able to resolve the conflicts to get this merged?

2021-07-20 03:52 UTC, akeel230 commented
@sure @Gravewalker666 ill resolve the conflict and push it to the PR

2021-07-20 03:56 UTC, akeel230 commented
@Gravewalker666 conflict resolved take a look

2021-07-20 03:57 UTC, akeel230 commented
![Screenshot (179)](https://user-images.githubusercontent.com/83522139/126259717-5fa3c0a7-d863-4647-b879-23374739b69a.png)
here u go please take a look @Gravewalker666

2021-07-21 04:30 UTC, anjula-sack requested changes

2021-07-21 04:30 UTC, anjula-sack commented on developers.json
> +
Remove this empty line

2021-07-21 04:36 UTC, akeel230 commented on developers.json
> +
@anjula-sack done. Thanks

2021-07-21 04:38 UTC, anjula-sack approved these changes

2021-09-14 12:06 UTC, closed without merging